### ISSUE TITLE
when use sdk create device service, and run local, but the created service not register to consul, why? 

### ISSUE THREAD

**Issue by zhui19871** [edgexfoundry/device-sdk-go#1003]

**Comment by hahattan** [comment]
I assumed you built your device service in binary and run it, you need to provide cmdline option (or environment variable) to register to consul.
For reference: https://docs.edgexfoundry.org/2.0/microservices/configuration/CommonCommandLineOptions/#registry

**Comment by zhui19871** [comment]
what cmdline? Will it be automatically registered when I configure it in the configuration file?

**Comment by zhui19871** [comment]
i see the cmdline, Will it be automatically registered when I configure it in the configuration file? not use cmdline way.

**Comment by hahattan** [comment]
Using environment variable is another option: https://docs.edgexfoundry.org/2.0/microservices/configuration/CommonEnvironmentVariables/#edgex_use_registry

**Comment by zhui19871** [comment]
Use the comline had register the service, but healthe check is failed, why? the api ping is ok.

**Comment by hahattan** [comment]
> but healthe check is failed, why?

Consul service needs to be able to access your device service. If you're deploying your consul and other edgex micro services in docker and run your device service in binary, you need to update the SERVICE_HOST configuration to your host IP address:https://github.com/edgexfoundry/device-sdk-go/blob/b8bde01b3040ded824082163a6ece586529576f1/example/cmd/device-simple/res/configuration.toml#L14

Otherwise please provide more detail on your deployment scenario.

**Comment by zhui19871** [comment]
Thanks, now is ok.
