### ISSUE TITLE
when update the device profile, and restart the device service, but get the device all commands is not updated? why?

### ISSUE THREAD

**Issue by zhui19871** [edgexfoundry/device-sdk-go#1007]
# 🐞 Bug Report

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**EdgeX Version:**

**Anything else relevant?**

**Comment by zhui19871** [comment]
Working in a Hybrid environment?

**Comment by zhui19871** [comment]
EdgeX Version: ireland, device service is local.

**Comment by cloudxxx8** [comment]
@zhui19871 since you are using hybrid environment, I suspect your core-metadata can't callback the Device Service correctly.
May I know the value of your service.host in the Device Service configuration? It should be the docker0 ip address, such as 172.17.0.1.

**Comment by lenny-intel** [comment]
@zhui19871, if you are updating the local device profile and the device service has already run previously, you must delete to old device profile from Core Metadata. Otherwise the device service sees that it already exists and doesn't upload the local file with your changes. See here for Core Metadata REST APIs:
Hanoi: https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/1.2.1
Ireland: https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.0.0
