### ISSUE TITLE
Review thread safety in devices.go

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#13]
The code in devices.go should be reviewed for thread safety.  The current implementation was based on the original EdgeX Java Device Services SDK.  This change is dependent on a new internal device struct to be created, so that devices can be locked when operations involving the device are in-progress.

**Estimated effort**: 2d

**Comment by tonyespy** [comment]
After discussion with @cloudxxx8, we decided that this still should be done.

**Comment by tsconn23** [comment]
internal/cache/devices.go

**Comment by tsconn23** [comment]
@cloudxxx8 In terms of literal "thread safety" yes, I think the code looks fine. If your concern is whether or not the maps in the deviceCache struct should be controlled by a mutex, I would say absolutely not because that will effectively single-thread the service. Also, in the case where a function loops through the deviceCache using a range, like this:

```
for _, device := range d.dMap {
    if device.Addressable.Id == add.Id {
        device.Addressable = add
            found = true
    }
}
```
The range expression `d.dMap` is evaluated once before the loop begins. If, while in the process of looping, the addressable is added, then the above loop will return false until the next time it is called. However, this is no different than doing a database lookup where the row you want is inserted right after you look for it.

So I think the above file is fine.

**Comment by cloudxxx8** [comment]
thanks, @tsconn23 
@tonyespy do you think we could close this issue now?

**Comment by cloudxxx8** [comment]
Is it better to use sync.Map?
https://golang.org/pkg/sync/#Map
