### ISSUE TITLE
Scale might be float data type even if the device resource type is integer

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#151]
For the example of CoolMasterNet
http://coolautomation.com/lib/doc/manual/Modbus-guidelines.pdf

The reading value of temperature is integer in device resource, such as 254 (Room Temperature x10 °C
), so the scale is a flow value- 0.1.  However, our current design would return the error message like
`ERROR: 2019/01/03 17:03:23 the scale 0.1 of PropertyValue cannot be parsed to int16: strconv.ParseInt: parsing "0.1": invalid syntax`

**Comment by jpwhitemn** [comment]
Encountered the same issue with a Modbus Comet temperature sensor.   Data in register is a whole integer like 215 for 21.5 degrees Celsius.  Would like to have the scale to be 0.1 and have the service return 21 (or 22).

**Comment by jpwhitemn** [comment]
That's fine Cloud.  At least it would allow for scales that are less than zero.
I think in the future (way in the future ) we might want to consider a profile that allows a user to specify the deviceResource type and a resource type that are different and allows for some amount of translation - but crawl first 
j

    On Sunday, January 13, 2019, 8:29:17 AM CST, cloudxxx8 <notifications@github.com> wrote:  
 
 
@jpwhitemn
If we apply #155, your example will get 21, because the default behavior is round down
