### ISSUE TITLE
cannot use bson.ObjectIdHex(id)

### ISSUE THREAD

**Issue by wangnuannuan** [edgexfoundry/device-sdk-go#152]
line 176 should be:

```
	ds.Service.Id = id 
	common.LoggingClient.Debug("New deviceservice Id: " + ds.Service.Id) 
```

**Comment by cloudxxx8** [comment]
@wangnuannuan thanks for reporting that.  the data type of Service.Id is just changed.  I will open PR to fix it by today.
By the way, please use the released and stable version (branch)- "delhi" for your evaluation

**Comment by cloudxxx8** [comment]
@wangnuannuan this issue is duplicated to https://github.com/edgexfoundry/device-mqtt-go/pull/17 and fixed by https://github.com/edgexfoundry/device-mqtt-go/pull/19
For device-mqtt, please set up MQTT broker first and modify configuration-driver.toml.  The related to document will be available in the community web site soon
