### ISSUE TITLE
Update Device SDK to use new Registry Abstraction

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#159]
This is dependent on edgex-go #1039 to be completed

Existing Consul code should be removed from the repo

**Comment by tonyespy** [comment]
@lenny-intel What's the ETA for completion of edgex-go #1039?

**Comment by tonyespy** [comment]
@tsconn23 Is the old consul code being added to the new contracts module? We're trying to determine if this issue has to be addressed for Edinburgh.

**Comment by lenny-intel** [comment]
@tonyespy , plan is to use the new go-mod-registry (#1039) in the device-sdk-go once it has be completed. Hoping to have the PR submitted next week after some internal Intel processes. I was planning to handle this issue.

**Comment by lenny-intel** [comment]
@tonyespy, I can't seem to find where the device-sdk-go is calling the existing CheckKeyValuePairs. I'd expected in in loader.go but IDE usage search shows no usage. What am I missing?

**Comment by cloudxxx8** [comment]
@lenny-intel That's right.  It doesn't use anymore, because it is the older implementation.  In fact, I have made one version for this feature.  Have you started implantation?  I will open PR tomorrow.  May you help review or take over to optimize the code?
@tonyespy In device sdk, there is a little different from edgex-go.  Since there is no config-seed support for now, we plan to populate the config from TOML to Consul when it starts up with --registry first time, and load from Consul in the future.  That's the C SDK current behavior.  The common part of Consul access could leverage after go-mod-registry ready.

**Comment by cloudxxx8** [comment]
@lenny-intel please help review this PR
https://github.com/edgexfoundry/device-sdk-go/pull/175

**Comment by lenny-intel** [comment]
@cloudxxx8 , thanks for the clarification. Yes I already have implementation using new Abstract Registry from go-mod-registry (PR coming soon). This will obsolete the changes you made for PR
#175. I will still review it to ensure I cover everything in my implementation.

**Comment by lenny-intel** [comment]
PR #186 addressed this issue.
