### ISSUE TITLE
Implement size constraints for devices & profiles

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#18]
Implement size constraints (w/unit tests) for devices and profiles based on configuration settings.  Constraints should include:

 * max devices (total & per profile)

 * max labels per device

 * max device profiles

 * max commands per device profile

 * max resource operations per device profile command

* max number of device resources

* max number of resource commands

* max number of resource operations (applies to get & put)

**Estimated effort**: 2-3d

**Comment by cloudxxx8** [comment]
Since the user requirements are various, we don't have a good standard to define a real constrain for all of them.  There is a customer using 40k device resource for OPC-UA.
We have MaxEventSize and MaxResultCount to constrain the size of payload.
https://github.com/edgexfoundry/edgex-go/blob/ebbd479b391021732e21bea19cf1ff2caaa95a06/cmd/core-data/res/configuration.yaml#L1
https://github.com/edgexfoundry/edgex-go/blob/ebbd479b391021732e21bea19cf1ff2caaa95a06/cmd/core-common-config-bootstrapper/res/configuration.yaml#L26

Decided in the Device WG 12-DEC-2023, it's enough for now, closing this issue.
