### ISSUE TITLE
Transition DSDK to New Support-Scheduler

### ISSUE THREAD

**Issue by tobiasmo1** [edgexfoundry/device-sdk-go#189]
An important target for Edinburgh release is the deprecation of Internal/Metadata Scheduler which is replaced by the [Support Scheduler service](https://github.com/edgexfoundry/edgex-go/tree/master/internal/support/scheduler). 

We need to transition **from** current go-mod-core-contracts data models: [Schedule](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/schedule.go) / [ScheduleEvent ](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/scheduleevent.go). These are currently exposed and available as an "internal scheduler" for Device SDK clients. However it is limiting due to reliance on [Core-Metadata](https://github.com/edgexfoundry/edgex-go/tree/master/internal/core/metadata) to manage schedule event data, and supplies the functionality exclusively to those who link and implement to the Device SDK.

The recently added [Support Scheduler](https://github.com/edgexfoundry/edgex-go/tree/master/internal/support/scheduler) service must be integrated so Device SDK instruments to the new Support Scheduler data models, and [scheduler client methods](https://github.com/edgexfoundry/go-mod-core-contracts/tree/master/clients/scheduler) for actuation. This improves our adherence to single responsibility and other [SOLID](https://deviq.com/solid/) principles.

Transition **to** the new go-mod-core-contracts data models: [Interval ](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/interval.go) / [IntervalAction](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/models/interval_action.go). 

New usage patterns should also be demonstrated within the [device-simple](https://github.com/edgexfoundry/device-sdk-go/blob/master/example/cmd/device-simple/res/configuration.toml) example.

Effort should include new and refactored unit and integration tests; located in device-sdk-go and blackbox-testing repositories.

**Comment by tsconn23** [comment]
@xmlviking for visibility

**Comment by xmlviking** [comment]
Looks good.  Thanks you.

**Comment by tonyespy** [comment]
Hmmm, this doesn't sound quite right to me.

The original Java SDK allowed for both internal SDK device service scheduling, and external scheduling (handled by Support Scheduler) in order to trigger readings from a device service on a scheduled basis. Both used `Schedule` and `ScheduleEvent`objects read from Core Metadata. Both also unfortunately used the same mechanism REST API calls to drive these events. For the internal case, this was unfortunate because it meant a service was making HTTP calls to itself.

For the initial version of the Go (and C?) SDK the same approach was used, however we fixed the internal SDK scheduler to skip the REST logic, and instead make an internal function/method calls.

Next, we had long discussions about whether it was appropriate for device services to be using objects that it was felt should be solely under the control of Support Scheduler. We decided it shouldn't, and therefore `AutoEvent` was invented to replace usage of `Schedule` and `ScheduleEvent` by the device SDKs.

I'm a bit puzzled about the appearance of `Interval` and `IntervalAction` (I'll note that neither have any associated godoc) as they look like clones of `Schedule` and `ScheduleEvent`. What's their purpose?

During last week's call we discussed whether or not the SDK should continue to support creation of `Schedule` and `ScheduleEvent` objects using the Support Scheduler client instead of the Core Metadata client, and I thought the agreement was no, it shouldn't do this.

I think what this issue really needs to be about is transitioning the internal SDK scheduler to use the new `AutoEvent` objects instead of `Schedule` and `ScheduleEvent`. This may include configuration code to allow creation of `AutoEvent` objects at startup as was formerly supported for `Schedule` and `ScheduleEvent` objects.

**Comment by tsconn23** [comment]
+1 to @tonyespy 's comments, We did say that there was no need to integrate with the Scheduler service and that AutoEvents would serve the purpose. This is captured in last week's [meeting notes](https://wiki.edgexfoundry.org/display/FA/Device+and+Device+SDK+Working+Group?preview=/329488/27492394/Device%20Service%20WG-3-4-19.pdf). I think that requirement should be removed from the issue.

As to `Interval` and `IntervalAction` it is my understanding as well that those replace `Schedule` and `ScheduleEvent` respectively. They were added by @xmlviking when he fleshed out the new support-scheduler. Perhaps I should create an issue for him to provide GoDoc content for the service as well.

**Comment by tobiasmo1** [comment]
AutoEvents allow device service to simulate a push of their readings as events; rather than being pulled from the external Support Scheduler. To me this is a consideration likely driven by systems requirements, _perhaps already resolved by the team_.

As the number of connected devices scales at the edge, given the impact on network and compute i/o, it seems particularly valuable for Scheduler, Rules Engine, Messaging and other device services to have ability to coordinate/tune event configuration across device services, along with other "schedule types" like health checks, etc.

Is visibility required by mvp Systems Management components as to the existence/frequency of such device polling events?  If so, would the mvp implementation of device polling (such as polling events that originate from configuration.toml) best suited to instrumenting Support Scheduler's external events, taking advantage of its centralized scheduling coordination/management? Was decision for autoevents based on Support Scheduler becoming a single point of failure?

**Comment by tobiasmo1** [comment]
AutoEvents to provide DS SDK functionality needed in Edinburgh. As an enhancement we will consider adding configuration.toml property to define local vs external schedules. With external invoking Support Scheduler Interval/IntervalActions.

**Comment by tonyespy** [comment]
@tobiasmo1 The missing piece for me was understanding that Interval/IntervalActions were meant as replacements for Schedule/ScheduleEvents. I'm not sure I totally agree with the rationale for creating them as opposed to continuing to use Schedule/ScheduleEvents, but that's not my domain...  Sorry for the confusion.

That said, I agree with deferring this issue to Fuji.

**Comment by SteveOss** [comment]
Ditto. I presumed Schedule and friends were remaining as is. The intent of Actions was to disambiguate
between local SDK polling type functionality and the more general (external) scheduling. In general I
don't believe the SDK should support the configuration of schedules, both because it introduces
unnecessary service coupling and because I see these sort of higher level scheduling activities as
belonging in the application domain.

**Comment by cloudxxx8** [comment]
@tobiasmo1 do you agree to close this issue and leave the responsibility of managing Interval/IntervalActions out side of Device Service SDK?

**Comment by jpwhitemn** [comment]
Per 9/16/2019 WG meeting, closing with option for Toby to reopen with more input/use case info.
