### ISSUE TITLE
Unregister from Registry when the Device Service stops

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#217]
Currently, when the Device Service stops gracefully, it doesn't unregester itself from Registry.

**Comment by lenny-intel** [comment]
Currently the Abstract Registry doesn't have an interface for Unregister, so that will need to be added to support this issue.

**Comment by tsconn23** [comment]
I don't know that it should unregister. The health check in Consul will fail if the service goes down. If the service unregisters, we wouldn't have that visibility.

**Comment by cloudxxx8** [comment]
if the IP address is dynamic and allow multiple instance of the same service, we might not want legacy IPs are kept.  On the other hand, we might need to know whether the service is stopped on purpose or encounter error.
It is normally part of the self-registration pattern.  I just bring up this topic, and we could discuss which approach we want.
https://microservices.io/patterns/self-registration.html
https://auth0.com/blog/an-introduction-to-microservices-part-3-the-service-registry/

**Comment by tsconn23** [comment]
Ah, I see. You're talking about normal shutdown in a high availability scenario -- auto-scaling for example. I think this might be a Fuji topic.

**Comment by tonyespy** [comment]
I think any service should be de-registering itself as part of normal shutdown. Otherwise, if a service's configuration changes and re-starts, how would it's service info get updated in the registry? If it doesn't un-register and it restarts, does the registry return an error when the service tries to register again? 

That said, we did say in the Service Name design document that a service should deregister itself when it responds to shutdown requests, which to me, means a shutdown request to the SMA REST endpoints each service exposes *or* a native shutdown mechanism (e.g. docker-compose down, snap disable, ...).

**Comment by tsconn23** [comment]
>if a service's configuration changes and re-starts, how would it's service info get updated in the registry?

Its configuration would have to be changed in the registry itself since services don't bootstrap their config.

>If it doesn't un-register and it restarts, does the registry return an error when the service tries to register again?

It would not throw an error. The health check would simply start passing again.

**Comment by akramtexas** [comment]
> I don't know that it should unregister. The health check in Consul will fail if the service goes down. If the service unregisters, we wouldn't have that visibility.
> 
> Perhaps the manual unregistering of a service might be a capability for the SMA @akramtexas

`Initial thoughts`
The manual unregistering of a service as a potential capability to be added to the SMA may make sense as a `second` (follow up) step to, `first`, incorporating a manifest mechanism in the SMA (thinking here of the `discoverability` aspects of services). Given such a sequencing, and hence the timing for its realization, I think this might be a Fuji topic.

This requires some clarification, but this is the perfect audience:
- The SMA will need to be provided a configuration (aka `manifest`) that specifies the list of the services it manages. The manifest will enumerate the services which the SMA is managing, along with details such as are needed to manage any given service. This mechanism is warranted by the need to onboard additional (device) services essentially, but this may well tie in with incorporating the manual unregistering of a service (as a potential capability to be added to the SMA).
- Thus, from the perspective of the SMA—and circling back here to the discoverability aspects—we have in place a check to determine whether the SMA is aware of a given service (via its associated ServiceKey) via a lookup to identify if the ServiceKey is one for which the SMA has a ready-made "client" (referring here to a client that is responsible for mediating between a given service and the SMA). If a service is unknown to the SMA, the Registry is queried to determine whether it (i.e. the service) is available. And given that the service is unknown to the SMA, the Registry is asked for a ServiceEndpoint associated with that service.
- And this is where the manifest mechanism comes in: The SMA will, at this juncture, lean on the provided configuration (aka manifest) to proceed with servicing the request. (_Dynamic_ generation of the needed config information comes to mind as a possibility, though this may not be feasible for the first pass of a possible implementation.)
- The alternate flow is that, for a service that is known to the SMA, there is no need to ask the Registry for a ServiceEndpoint associated with that service: The SMA simply uses one of the ready-made list of clients that was created at bootstrap, thus using the config that's driven by statically-defined keys (one each for the core services) 
- With such a `manifest` mechanism in place, incorporating the manual unregistering of a service (as a potential capability to be added to the SMA) could tie in as a `second` step, with that (i.e. the `Boolean` state of whether a service is registered, or not) perhaps captured via a setting in the `manifest`.

**Comment by tsconn23** [comment]
So @akramtexas the manifest is for use in cases where there isn't a Registry involved. When there is a Registry involved, the issue is whether or not services should unregister themselves upon graceful shutdown. I think @cloudxxx8 and @tonyespy are advocating that they should.

My original question is based on the fact that we do not currently have an Unregister() method in the Registry abstraction, and I was throwing out the possibility of the SMA performing the unregister in lieu of adding that method. For example, if a service were to crash and could not be brought back up.

**Comment by akramtexas** [comment]
Thanks @tsconn23 for clarifying the use case details. With that, I will revisit the possibility of the SMA performing the `unregister` operation in lieu of adding the `Unregister()` method 👍

**Comment by iain-anderson** [comment]
What should occur in the scenario where the registry is in use and a service's configured port is changed?
The service can be notified of the update to its configuration and reconfigure its own endpoint accordingly, but can it then update its registration information in the registry, and can this update be notified to the other running services?

**Comment by tsconn23** [comment]
@iain-anderson In the core services that would require a service restart since the port is not in the `Writable` section of the config. Service A would register itself using the new port after restart. Service B should use a client implementing the [Endpointer](https://github.com/edgexfoundry/go-mod-core-contracts/blob/e53159cfbe2cc8832483252ada48f1a5475584f6/clients/endpointer.go#L21) interface to refresh Service A's endpoint from the registry via service key. There are more sophisticated ways to do this, but right now the Endpointer will refresh an endpoint from the registry on a configured interval.

**Comment by iain-anderson** [comment]
OK thanks

**Comment by iain-anderson** [comment]
Would it be better (SSOT) to have Endpointer work by reading the other service's configuration directly?

**Comment by tsconn23** [comment]
@iain-anderson If a service is started with `--registry` then it needs to use the registry because that's  the centralized location of current configuration information. An endpoint host/port may not be defined by config as in the case of a cloud/HA deployment. In this case a service instance may also go away unexpectedly due to scaling, or there could be multiple instances behind a single service key with a load balancer in the middle.

**Comment by cloudxxx8** [comment]
Need the support from go-mod-registry.  The issue to request this feature is opened
https://github.com/edgexfoundry/go-mod-registry/issues/20

**Comment by cloudxxx8** [comment]
@hahattan please verify it is handled by go-mod-bootsrap

**Comment by lenny-intel** [comment]
@hahattan, check the log file for `un-registered` message
