### ISSUE TITLE
device-sdk-go encodes events twice when responding to a command REST call

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#233]
When a successful REST API call is made to a device service's command endpoint, the SDK creates an event containing one or more readings and:

 * sends it to Core Data's event endpoint as CBOR or JSON
 * sends it to the caller as CBOR or JSON

As currently implemented the encoding of the event and readings it contains is done twice, once in the core-contracts event client [Add](https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/coredata/event.go#L143) method, and once in the device-sdk-go's [commandFunc](https://github.com/edgexfoundry/device-sdk-go/blob/master/internal/controller/restfuncs.go#L86) function.

Ideally we'd only do this encoding once...

**Comment by tsconn23** [comment]
> Ideally we'd only do this encoding once...

I think by the above comment you mean "Ideally we'd only implement the encoding in one place" b/c the core-contracts aren't involved in this operation as far as I can tell. It's not that we're encoding something twice in one execution path, it's that there's two different places where the encoding is carried out.

I'm actually not clear what's happening to the event here because the only way to get an event into core-data that I'm aware of is via [HTTP POST](https://github.com/edgexfoundry/edgex-go/blob/9de1bcaf08e82f14fdde703f16ebe68ce24f74fa/internal/core/data/router.go#L204). Here it looks like the event is being written directly back to the caller of the device service. And if the caller of the device service is core-command, then core-command in turn [returns the event](https://github.com/edgexfoundry/edgex-go/blob/9de1bcaf08e82f14fdde703f16ebe68ce24f74fa/internal/core/command/restDevice.go#L49) to its caller. Is that a legit flow? If so, it's not really an Event in the same manner that we usually talk about them. I'm not aware of anything in EdgeX that would make a call like this (since the rules engine subscribes to export-distro) so it would presume some kind of northside 3rd party invoking a GET command on the device service...which isn't possible right now.

**Comment by tobiasmo1** [comment]
If there is time, could we cover this topic at Core WG tomorrow?

**Comment by tonyespy** [comment]
When Core Command makes a query (a Get REST call) to a device service, the response payload is the same JSON encoded Event as gets sent to Core Data. Core Command indeed passes this response along to an external called (although I doubt we have a black box test to verify this). So there is a single execution path in a device service where an event and the readings it contains are JSON encoded twice; once in the core-contract's event client, and once in the device service's top-level REST controller.

**Comment by cloudxxx8** [comment]
@hahattan please help verify whether this issue is fxied

**Comment by hahattan** [comment]
I think this issue is resolved by #293. SDK will check if event is encoded or not, if not it'll encode via [MarshalEvent](https://github.com/edgexfoundry/go-mod-core-contracts/blob/9132f554263fd61cb848f5b965b4d1aa9442ed97/clients/coredata/event.go#L187) in go-mod-core-contracts
