### ISSUE TITLE
Changes to AutoEvents don't take effect unless Device removed from DB

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-go#256]
When I change auto events configuration in the toml file and restart the device service the changes don't take effect unless I first remove the device from the DB.

**Comment by tobiasmo1** [comment]
This remains the case for *any* cached resource/device/obj that gets stored.

**Comment by cloudxxx8** [comment]
It is the expected behavior.  AutoEvent is not from configuration, but from Device instances.  The pre-defined DeviceList in configuration is only created first time.  After that, you have to send update call to core-metadata to update the Device data, including AutoEvent.  Callback will notify Device Service to run the updated AutoEvent.

The reason you clean up the DB can work is that DeviceList in configuration is loaded and re-created.
You cannot depend on configuration to update the pre-defined Devices, or we have to change the requirement and design.

**Comment by iain-anderson** [comment]
Yeah, the device service provides a minimal provisioning facility whereby it will create devices and profiles from the conf file and .yaml files if those entities don't already exist.
I think this would better be done in a standalone tool, then options could be added for update/delete operations

**Comment by lenny-intel** [comment]
Ok, It is just awkward that changes to the settings in the configuration.toml file don't take effect when the service is restarted. For Fuji, should these values be in the profile yaml files rather than the configuration.toml? Then it would be obvious that they don't take effect until DB is updated.

**Comment by cloudxxx8** [comment]
we can discuss the solution in the face to face meeting.  If we update Device from configuration whenever the Device Service start up, all the changes in core-metadata will be restore each time.  Normally, users won't update Device through configuration, and those section won't be sync to Consul.  I agree with moving them out from configuration

**Comment by cloudxxx8** [comment]
@lenny-intel do you think it is still a valid issue?  For the move of device our from the configuration, it should be a separated issue.  Thanks.

**Comment by lenny-intel** [comment]
@cloudxxx8 , agreed.
