### ISSUE TITLE
Events and Readings should be timestamped in nanoseconds

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#273]
According to the architecture decision in face to face meeting, we would use nanoseconds in Events and Readings to get more accuracy

**Comment by SteveOss** [comment]
There was also the point that could use, or wrap, a nanosecond clock so that each reading would have
a unique timestamp (this only fails if a device service can generate more than 1,000,000,000 readings
per second). This in combination with a unique device service identifier, means that all events can be
uniquely identified.
