### ISSUE TITLE
Implement command unit tests

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-sdk-go#28]
Implement unit tests for the command endpoint (GET & PUT).

This relies on a few other tasks being completed first, namely ensuring that there are interfaces for needed clients and the caching code so that things can be mocked.

**Estimated effort**: 5-7d

**Comment by tsconn23** [comment]
FYI I've started working on this. I was blocked this afternoon on other stuff, so I started looking at this issue as a way to become more familiar with the Device SDK. I have implemented one unit test so far. Most of my time has been spent trying to decouple the existing logic so that it can be testable in the first place. You can find my progress in this feature branch.
https://github.com/tsconn23/device-sdk-go/tree/issue_28

Some principles I'm trying to align toward
- Interfaces should be declared in the package where they are used (ease of mocking)
- Interfaces should only contain methods that are used internally within the package (again, ease of mocking)
- Separation of responsibilities. Each function should ideally do one thing, making it easy to test. Also, everything the function needs should be provided via the parameters or by an encapsulating type.
- Elimination of static resources (for example we access the various caches all over the place and at whim)
- Where it makes sense create types that can manage a more complex operation and hold context for the composable internal functions

**Comment by tsconn23** [comment]
Making notes as I go --

- There is currently no way to initialize an individual cache for testing purposes. The only way to create a cache is to call `/internal/cache/init.go::InitCache()`. This makes live service calls to populate cache entities. I can't make live service calls during a unit test, and additionally I only want to populate the caches relevant to my test.
- The above will require expanding the cache contract so that methods are exported whereby an individual cache (such as Profiles) can be created.
- Example: `func newProfileCache(profiles []models.DeviceProfile) *profileCache` will probably need to be exported.

**Comment by cloudxxx8** [comment]
@tsconn23 should we open another issue to improve the testablility or modify them with this issue?

**Comment by cloudxxx8** [comment]
We might be able to test by implementing the mock caches because they are interface now

**Comment by cloudxxx8** [comment]
@tsconn23 please help take a look the work from @FelixTing
https://github.com/FelixTing/device-sdk-go/commit/6bc748ab6022e9dab4dc4e1ca2e1895a16ca077a

He modified your work without the refactoring.  If you agree, he could help accomplish the unit test for this release.

**Comment by cloudxxx8** [comment]
@tsconn23 May we take over this task by copying your existing test with the current code structure?
Then, we could open another issue to make further refactoring in fuji

**Comment by tsconn23** [comment]
@cloudxxx8 That's fine. I'm not focused on this at the moment.

**Comment by cloudxxx8** [comment]
thanks, Trevor
@FelixTing , please continue to work on this item.
