### ISSUE TITLE
Use NewSimpleReading and NewBinaryReading factory method in transform

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-go#788]
We should use factory method to create the DTOs

**Comment by hahattan** [comment]
@cloudxxx8 @lenny-intel @iain-anderson 
as the NewSimpleReading factory method receive interface and will convert to the specific type for us:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/0e379c9e0edea5f92b57b16d86d7cadc9bd580f4/v2/dtos/reading.go#L62-L63

Do we need to update the usage of `CommandValue`, otherwise there will be at least 2 unnecessary data transformation.
For example:
when driver implementation get a uint8 value, developer need to first call `NewUint8Value`(which encode numeric value to []byte) to return `CommandValue` for SDK:
https://github.com/edgexfoundry/device-sdk-go/blob/6125dba09cfc805438589ab7aad954d8cad7589e/pkg/models/commandvalue.go#L86

and in SDK if we want to use the factory method we need to transform the []byte back to uint8 again.
